### ISSUE TITLE
Missing a licence

### ISSUE THREAD

**Issue by Moosemorals** [nunit/nunit-transforms#16]
Could you please add a licence to the repository so I can use the nunit3-junit filter in another project. Thanks

**Comment by mikkelbu** [comment]
@Moosemorals I cannot answer this question and add a license - @CharliePoole probably can - but at least it seems like two of the transforms `nunit3-summary` and `nunit2-summary` are extracted from a project - https://github.com/charliepoole/nunit-summary - which has a MIT license.

**Comment by CharliePoole** [comment]
@Moosemorals To clarify what @mikkelbu has said, it's a contrib project and each contributor has the rights to their own contribution. So while any of us on the Core Team have write access, a license we added would be a fabrication. It's up to the actual contributor to license it. (This is different from contributions to the actual NUnit projects, which automatically fall under our license.)

I'll add a license to my own two contributions and perhaps @tenwit will see this and add a license file to his. :smile: 

@nunit/core-team Maybe we want to get rid of this project.

**Comment by Moosemorals** [comment]
> Maybe we want to get rid of this project.

Oh, gods, that's exactly what I didn't want!

**Comment by CharliePoole** [comment]
@Moosemorals Sorry, didn't mean to shock you... I was thinking out loud.

Thing is, I don't know if it's worth while to have a project that nobody maintains. But since we have it, maybe just putting something in the Readme about who to contact for each contribution would resolve the problem.

**Comment by mikkelbu** [comment]
I think the suggestion is fine. I was considering if this could be a couple of Github gists, but perhaps a project like this is more discoverable. The Readme could also mention that this is largely unmaintained

**Comment by CharliePoole** [comment]
@mikkelbu See what you think of PR #17

**Comment by tenwit** [comment]
I'm happy with any license. This work is gifted to NUnit and I'm happy with anyone using it any way they like.
I maintained the xslt back when Jenkins couldn't handle the NUnit results xml files. These days it can, so I don't use this code any more.

**Comment by CharliePoole** [comment]
@tenwit I've just recently agreed to serve as overall maintainer for this project, so I'm working to clean things up a bit. I can add the MIT license with your name if you like.

Since @Moosemorals actually needs this, it's no doubt more useful than we realize... some other software that doesn't understand NUnit 3 format I imagine.

**Comment by CharliePoole** [comment]
@tenwit Shall I mark it as no longer maintained?

**Comment by CharliePoole** [comment]
After some offline discussion with @tenwit an MIT License has been added.
