### ISSUE TITLE
Transform fails to produce valid junit.xml when Assertions element is present

### ISSUE THREAD

**Issue by julianchurchill** [nunit/nunit-transforms#5]
I'm using the nunit-junit.xslt to transform the TestResults.xml produced by dotnet-test-nunit 3.4.0-beta-3. I'm using the Powershell script from the README.md to do this in a Jenkins job step.

This works well, except when a unit test failure occurs. The produced junit xml is not valid as it ends up with some plain text outside of any xml elements but in between consecutive <failure> elements inside a test case. This appears to be coming from <attribute> elements in the original nunit3 TestResults.xml. For example the output looks like this:
```
<?xml version="1.0" encoding="UTF-8" ?>
   <testsuites id="1" name="some test suites" tests="1" failures="1" time="0.001">
      <testsuite id="tests.mytests" name="some test suite name" tests="1" failures="1" time="0.001">
         <testcase id="tests.mytests.alovelytestcase" name="some test name" time="0.001">
            <failure message="This test has definitely failed">
This test has definitely failed
      </failure>
This text shouldn't be here but was wrapped up in assertion elements in TestResults.xml
    </testcase>
  </testsuite>
</testsuites>
```

Is there a missing '<xsl:template match="attributes"/>' statement in the xslt or am I doing something wrong?

**Comment by rprouse** [comment]
@julianchurchill that transform was contributed to the NUnit project. Hopefully the original contributor can help, @tenwit, any ideas?

**Comment by tarfert** [comment]
I've solved this by adding an empty `xsl:template` explicit for `test-case/assertions`. This way the XSLT transformer does not incorrectly match to other templates.

https://github.com/nunit/nunit-transforms/pull/6
